version: 2

models:
  - name: stg_orders_recrutement
    description: >
      Staging model for orders. Standardizes raw orders data:
      Renames columns and cast types for analysis

    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - not_null
          - unique
        
      - name: customer_id
        description: Unique identifier for the customer who placed the order
        tests:
          - not_null

      - name: order_date
        description: Date when the order took place
        tests:
          - not_null

      - name: net_sales
        description: Total amount of the order in currency units
  
  - name: stg_sales_recrutement
    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - not_null
        
      - name: product_id
        description: Unique identifier for each product
        tests:
          - not_null
      
      - name: quantity
        description: Total quantity of the identified ordered by the customer in the order
        tests:
          - not_null
      
      - name: net_sales
        description: Sale value generated by the product in the identified order, in currency unit